### PR TITLE
Docker best practices

### PR DESCRIPTION
**Pull request by Naramsim**
Hi, better to merge after #29

### CODE REVIEW

**Review by juz501 — CHANGES_REQUESTED** [review]
Is there a better way to put that Postgres user password instead of plain text on the repo?

**Comment by tdmalone** [comment]
@juz501 As I understand it the Dockerfile needs something to set it up with, and it's really just to bootstrap the environment. The user could change it if they wish. It's also only intended for local set up; the port should never be accessible to the public.

**Comment by juz501** [comment]
Maybe we can do something like https://www.google.com.au/amp/s/davidwalsh.name/docker-compose-override/amp

**Comment by tdmalone** [comment]
Oh.. interesting. What do you think @Naramsim? From a comment on that article it looks like Docker Composer will also natively support `.env` files so that might be cleaner given we're already using it. However.... it does add another configuration step for the user. I'm not sure this is any different to eg. MySQL shipping with a default root password?

**Comment by Naramsim** [comment]
@tdmalone @juz501 I will look into it.

**Pull request closed without merging**
